/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 07-Dec-2019 5:02:30 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `box` CASCADE
;

DROP TABLE IF EXISTS `reservation` CASCADE
;

DROP TABLE IF EXISTS `tool` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `box`
(
	`BOX_ID` INT NOT NULL,
	`ADDRESS` VARCHAR(50) NOT NULL COMMENT 'Adress of code lock box',
	`NUMBER` INT NOT NULL COMMENT 'Box identification number -  printed on front of box',
	CONSTRAINT `PK_BOX` PRIMARY KEY (`BOX_ID` ASC)
)
COMMENT = 'Location where the tool can be picked up.'

;

CREATE TABLE `reservation`
(
	`RESERVATION_ID` INT NOT NULL,
	`USER_ID` INT NOT NULL,
	`TOOL_ID` INT NOT NULL,
	`BOX_ID` INT NULL,
	`DATE_OF_RESERVATION` DATE NOT NULL COMMENT 'Start date of reservation - this is the day the user has to pick up the tool that was reserved',
	`DATE_OF_RETURN` DATE NOT NULL COMMENT 'Return date - last day to return the rented tool before it is considered late',
	`ACTIVE` BOOLEAN NULL,
	CONSTRAINT `PK_RESERVATION` PRIMARY KEY (`RESERVATION_ID` ASC)
)

;

CREATE TABLE `tool`
(
	`TOOL_ID` INT NOT NULL COMMENT 'Tool identification number.',
	`NAME` VARCHAR(50) NOT NULL COMMENT 'Tool brand name',
	`PRICE` INT NOT NULL,
	`STATE` VARCHAR(8) NOT NULL,
	CONSTRAINT `PK_TOOL` PRIMARY KEY (`TOOL_ID` ASC)
)
COMMENT = 'One specific instance of tool.'

;

CREATE TABLE `user`
(
	`USER_ID` INT NOT NULL,
	`KARMA` INT NOT NULL COMMENT 'Karma is an attribute that increases or decreases based on the user''s renting history. It increases for rents that proceed without problems, and decreases for late pickups or returns, or for damaging tools.
	
	High karma can lead to discounts on subscriptions, while low karma can lead to fines or bans.',
	`FIRST_NAME` VARCHAR(30) NOT NULL,
	`SECOND_NAME` VARCHAR(30) NOT NULL,
	`EMAIL` VARCHAR(30) NOT NULL,
	`PHONE` VARCHAR(15) NULL,
	`PASSWORD` VARCHAR(30) NOT NULL,
	CONSTRAINT `PK_USER` PRIMARY KEY (`USER_ID` ASC)
)
COMMENT = 'User which uses the system.'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `reservation` 
 ADD INDEX `IXFK_RESERVATION_BOX` (`BOX_ID` ASC)
;

ALTER TABLE `reservation` 
 ADD INDEX `IXFK_RESERVATION_TOOL` (`TOOL_ID` ASC)
;

ALTER TABLE `reservation` 
 ADD INDEX `IXFK_RESERVATION_USER` (`USER_ID` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `reservation` 
 ADD CONSTRAINT `FK_RESERVATION_BOX`
	FOREIGN KEY (`BOX_ID`) REFERENCES `box` (`BOX_ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `reservation` 
 ADD CONSTRAINT `FK_RESERVATION_TOOL`
	FOREIGN KEY (`TOOL_ID`) REFERENCES `tool` (`TOOL_ID`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `reservation` 
 ADD CONSTRAINT `FK_RESERVATION_USER`
	FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 

INSERT INTO `user` (`USER_ID`, `KARMA`, `FIRST_NAME`, `SECOND_NAME`, `EMAIL`, `PASSWORD`) VALUES ('1', '0', 'Test', 'Test', 'user@test.com', '123456');

INSERT INTO `tool` (`TOOL_ID`, `NAME`, `PRICE`, `STATE`) VALUES ('1', 'Screwdriver', '100', 'FREE');
INSERT INTO `tool` (`TOOL_ID`, `NAME`, `PRICE`, `STATE`) VALUES ('2', 'Hammer', '112', 'FREE');
INSERT INTO `tool` (`TOOL_ID`, `NAME`, `PRICE`, `STATE`) VALUES ('3', 'Saw', '1045', 'FREE');
INSERT INTO `tool` (`TOOL_ID`, `NAME`, `PRICE`, `STATE`) VALUES ('4', 'Ladder', '450', 'FREE');
INSERT INTO `tool` (`TOOL_ID`, `NAME`, `PRICE`, `STATE`) VALUES ('5', 'Drill', '741', 'FREE');

INSERT INTO `box` (`BOX_ID`, `ADDRESS`, `NUMBER`) VALUES ('1', 'Bikbaya 37', '69');
INSERT INTO `box` (`BOX_ID`, `ADDRESS`, `NUMBER`) VALUES ('2', 'Olympiska 1901', '322');
INSERT INTO `box` (`BOX_ID`, `ADDRESS`, `NUMBER`) VALUES ('3', 'Baker Street 45', '1337');
INSERT INTO `box` (`BOX_ID`, `ADDRESS`, `NUMBER`) VALUES ('4', 'Tole Bi 84', '488');

